/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.forme;


import rs.ac.bg.fon.ai.nprog.MvnRecepcijaBiblioteka.domen.Gost;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.kontroler.Kontroler;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.sesija.Mapa;

/**
 *
 * @author Jelena Sreckovic
 */
public class GuestForma extends javax.swing.JDialog {
    
    /**
     * Creates new form UserForma
     */
    public GuestForma(java.awt.Frame parent, boolean modal, FormMode formMode) {
        super(parent, modal);
        initComponents();
        
        prepareForm(formMode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtGuestName = new javax.swing.JTextField();
        jTxtGuestLastname = new javax.swing.JTextField();
        jTxtGuestIDCard = new javax.swing.JTextField();
        jTxtGuestPhoneNumber = new javax.swing.JTextField();
        jTxtGuestEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnEnableChanges = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jBtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Please enter guest information..");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Guest infomation"));

        jLabel1.setText("Name:");

        jLabel2.setText("Last name:");

        jLabel3.setText("ID card:");

        jLabel4.setText("Phone number:");

        jLabel5.setText("E-mail:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtGuestName)
                            .addComponent(jTxtGuestLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtGuestIDCard)
                            .addComponent(jTxtGuestPhoneNumber)
                            .addComponent(jTxtGuestEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtGuestLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtGuestIDCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtGuestPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22))
        );

        jBtnCancel.setText("Cancel");

        jBtnSave.setText("Save");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });

        jBtnEnableChanges.setText("Enable changes");
        jBtnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnableChangesActionPerformed(evt);
            }
        });

        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBtnEnableChanges)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancel)
                .addGap(18, 18, 18)
                .addComponent(jBtnSave)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEnableChanges)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnDelete))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSave)
                    .addComponent(jBtnCancel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        String name = jTxtGuestName.getText().trim();
        String lastName = jTxtGuestLastname.getText().trim();
        String phone = jTxtGuestPhoneNumber.getText().trim();
        String idCard = jTxtGuestIDCard.getText().trim();
        String email = jTxtGuestEmail.getText().trim();
        
        if(name.isEmpty() || lastName.isEmpty() || phone.isEmpty() || idCard.isEmpty() || email.isEmpty()) {
            jTextArea1.setText("Sva polja su obavezna");
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira gosta");
            return;
        }
        
        jTextArea1.setText("");
        
        Gost g = new Gost(null,name,lastName, idCard, phone, email, Mapa.getInstanca().getReceptionist());
        
        
        Kontroler.getInstanca().sacuvajGosta(g);
        
        
        //prepareForm(FormMode.FORM_VIEW);
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        //PRVO PITAJ DA LI JE SIGURAN PA BRISI
        
        //Gost g = new Gost(null,name,lastName, idCard, phone, email, Controller.getInstance().getReceptionist());//kreiraj gosta, ulogovani recepcioner
        Gost g = Mapa.getInstanca().getGuest();
        
        Kontroler.getInstanca().obrisiGosta(g);
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnableChangesActionPerformed
        prepareForm(FormMode.FORM_UPDATE);
    }//GEN-LAST:event_jBtnEnableChangesActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        String name = jTxtGuestName.getText().trim();
        String lastName = jTxtGuestLastname.getText().trim();
        String phone = jTxtGuestPhoneNumber.getText().trim();
        String idCard = jTxtGuestIDCard.getText().trim();
        String email = jTxtGuestEmail.getText().trim();
        
        Gost g = new Gost(Mapa.getInstanca().getGuest().getGostID(),name,lastName, idCard, phone, email, Mapa.getInstanca().getReceptionist());//kreiraj gosta, ulogovani recepcioner
        
        Kontroler.getInstanca().izmeniGosta(g);
        
        //Mapa.getInstanca().setGuest(g);
        Kontroler.getInstanca().postaviGosta(g);
        prepareForm(FormMode.FORM_VIEW);
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnEnableChanges;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtGuestEmail;
    private javax.swing.JTextField jTxtGuestIDCard;
    private javax.swing.JTextField jTxtGuestLastname;
    private javax.swing.JTextField jTxtGuestName;
    private javax.swing.JTextField jTxtGuestPhoneNumber;
    // End of variables declaration//GEN-END:variables

    private void prepareForm(FormMode formMode) {
        //popuni sta treba, ako treba
        setLocationRelativeTo(null);
        if(formMode.equals(FormMode.FORM_ADD)) {
            //vidi ya polje ID
            jTextArea1.setEnabled(false);
            
            jBtnDelete.setVisible(false);
            jBtnUpdate.setVisible(false);
            jBtnEnableChanges.setVisible(false);
        }
        
        if(formMode.equals(FormMode.FORM_VIEW)) {
            jBtnSave.setVisible(false);
            jBtnDelete.setVisible(true);
            jBtnUpdate.setVisible(false);
            jBtnEnableChanges.setVisible(true);
            
            jTxtGuestName.setEditable(false);
            jTxtGuestLastname.setEditable(false);
            jTxtGuestIDCard.setEditable(false);
            jTxtGuestPhoneNumber.setEditable(false);
            jTxtGuestEmail.setEditable(false);
            jTextArea1.setEditable(false);
            
            Gost g = (Gost) Mapa.getInstanca().getGuest();
            System.out.println("uzeo gosta " + g.getImeGosta());
            fillForm(g);
        }
        
        if(formMode.equals(FormMode.FORM_UPDATE)) {
            
            jBtnDelete.setVisible(false);
            jBtnUpdate.setVisible(true);
            jBtnEnableChanges.setVisible(false);
            jTextArea1.setEnabled(false);
            
            jTxtGuestName.setEditable(true);
            jTxtGuestLastname.setEditable(true);
            jTxtGuestIDCard.setEditable(true);
            jTxtGuestPhoneNumber.setEditable(true);
            jTxtGuestEmail.setEditable(true);
            
            
        }
    }

    private void fillForm(Gost g) {
        jTxtGuestName.setText(g.getImeGosta());
        jTxtGuestLastname.setText(g.getPrezimeGosta());
        jTxtGuestIDCard.setText(g.getBrojLicneKarte());
        jTxtGuestPhoneNumber.setText(g.getBrojTelefona());
        jTxtGuestEmail.setText(g.getEmail());
        System.out.println("popunio formu");
        
    }

    public void prikaziPoruku(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
        //dispose();
    }
}
