/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.forme;


import javax.swing.JDialog;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.kontroler.Kontroler;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.sesija.Mapa;

/**
 *
 * @author Win10
 */
public class MainForma extends javax.swing.JFrame {
    /**
     * Creates new form MainForma
     */
    public MainForma() {
        initComponents();
        
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblUlogovani = new javax.swing.JLabel();
        jBtnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGuest = new javax.swing.JMenu();
        jMenuItemGuestNew = new javax.swing.JMenuItem();
        jMenuItemGuestSearch = new javax.swing.JMenuItem();
        jMenuBooking = new javax.swing.JMenu();
        jMenuItemBookingNew = new javax.swing.JMenuItem();
        jMenuItemBookingSearch = new javax.swing.JMenuItem();
        jMenuRooms = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblUlogovani.setText("Ulogovani ste kao:");

        jBtnLogout.setText("LOGOUT");
        jBtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogoutActionPerformed(evt);
            }
        });

        jMenuGuest.setText("Guest");

        jMenuItemGuestNew.setText("New");
        jMenuItemGuestNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuestNewActionPerformed(evt);
            }
        });
        jMenuGuest.add(jMenuItemGuestNew);

        jMenuItemGuestSearch.setText("Search");
        jMenuItemGuestSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuestSearchActionPerformed(evt);
            }
        });
        jMenuGuest.add(jMenuItemGuestSearch);

        jMenuBar1.add(jMenuGuest);

        jMenuBooking.setText("Booking");

        jMenuItemBookingNew.setText("New");
        jMenuItemBookingNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookingNewActionPerformed(evt);
            }
        });
        jMenuBooking.add(jMenuItemBookingNew);

        jMenuItemBookingSearch.setText("Search");
        jMenuItemBookingSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBookingSearchActionPerformed(evt);
            }
        });
        jMenuBooking.add(jMenuItemBookingSearch);

        jMenuBar1.add(jMenuBooking);

        jMenuRooms.setText("Room");
        jMenuBar1.add(jMenuRooms);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jBtnLogout)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblUlogovani)
                    .addComponent(jBtnLogout))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGuestNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuestNewActionPerformed
      /*JDialog form = new GuestForma(this, true, FormMode.FORM_ADD);
      form.setVisible(true);*/
      Kontroler.getInstanca().gostForma(this);
    }//GEN-LAST:event_jMenuItemGuestNewActionPerformed

    private void jMenuItemGuestSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuestSearchActionPerformed
        /*JDialog form = new SearchGuestForma(this, true, FormMode.FORM_UPDATE);
        form.setVisible(true);*/
        Kontroler.getInstanca().pretraziGostForma(this);
    }//GEN-LAST:event_jMenuItemGuestSearchActionPerformed

    private void jMenuItemBookingNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookingNewActionPerformed
        /*JDialog form = new ZakupForma(this, true, FormMode.FORM_ADD);
        form.setVisible(true);*/
        Kontroler.getInstanca().zakupForma(this);
    }//GEN-LAST:event_jMenuItemBookingNewActionPerformed

    private void jMenuItemBookingSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBookingSearchActionPerformed
        /*JDialog form = new SearchZakupForma(this, true);
        form.setVisible(true);*/
        Kontroler.getInstanca().pretraziZakupForma(this);
    }//GEN-LAST:event_jMenuItemBookingSearchActionPerformed

    private void jBtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogoutActionPerformed
        Kontroler.getInstanca().odjaviRecepcionera();
        //ne stigne da primi poruku da je izlogovan, pa prikayuje isto kao da je pao server
        
    }//GEN-LAST:event_jBtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JLabel jLblUlogovani;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBooking;
    private javax.swing.JMenu jMenuGuest;
    private javax.swing.JMenuItem jMenuItemBookingNew;
    private javax.swing.JMenuItem jMenuItemBookingSearch;
    private javax.swing.JMenuItem jMenuItemGuestNew;
    private javax.swing.JMenuItem jMenuItemGuestSearch;
    private javax.swing.JMenu jMenuRooms;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        jLblUlogovani.setText("Ulogovani ste kao: "+Mapa.getInstanca().getReceptionist());
        
    }
}
