/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.forme;

import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.component.table.model.RentTableModel;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaBiblioteka.konstante.Forme;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaBiblioteka.domen.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.kontroler.Kontroler;
import rs.ac.bg.fon.ai.nprog.MvnRecepcijaKlijent.sesija.Mapa;

/**
 *
 * @author Win10
 */
public class SearchZakupForma extends javax.swing.JDialog {

    /**
     * Creates new form SearchZakupForma
     */
    public SearchZakupForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareForm();
        popuniCombo();
        popuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtIdCard = new javax.swing.JTextField();
        jTxtName = new javax.swing.JTextField();
        jTxtLastname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtRoomNumber = new javax.swing.JTextField();
        jComboRoomTypes = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnSearch = new javax.swing.JButton();
        jBtnEnableChanges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search criteria:"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Guest informations:"));

        jLabel1.setText("ID card:");

        jLabel2.setText("Name:");

        jLabel3.setText("Lastname:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtIdCard, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jTxtName)
                    .addComponent(jTxtLastname))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtIdCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Room informations:"));

        jLabel4.setText("Room number:");

        jLabel5.setText("Room type:");

        jComboRoomTypes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(61, 61, 61)
                        .addComponent(jTxtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(jComboRoomTypes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jComboRoomTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Result:"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jBtnEnableChanges.setText("Enable changes for selected rent");
        jBtnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnableChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBtnSearch)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jBtnEnableChanges)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSearch)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jBtnEnableChanges)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        String idcard = jTxtIdCard.getText().trim();
        String ime = jTxtName.getText().trim();
        String prez = jTxtLastname.getText().trim();
        String broj = jTxtRoomNumber.getText().trim();
        VrstaSobe vs = (VrstaSobe) jComboRoomTypes.getSelectedItem();
        
        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();
        
        
        /*List<String> columnsG = new ArrayList<>();
        List<String> valuesG = new ArrayList<>();
            
        List<String> columnsS = new ArrayList<>();
        List<String> valuesS = new ArrayList<>();*/
        
        RentTableModel rtm = (RentTableModel) jTable1.getModel();
        
        if(idcard.isEmpty() && ime.isEmpty() && prez.isEmpty() && broj.isEmpty() && vs==null) {
            
            /*Request r = new Request();
            r.setOperation(Operacije.VRATI_SVE_ZAKUPE);
            Komunikacija.getInstance().posaljiZahtev(r);*/
            
            Kontroler.getInstanca().vratiSveZakupe();
            
            /*Response response = Komunikacija.getInstance().primiOdgovor();
            
            
            List<ZakupSobe> nadjeniZakupi = (List<ZakupSobe>) response.getResponse();
            rtm.setZakupi(nadjeniZakupi);*/
            
        } else {
        
        if(!idcard.isEmpty()) {
            columns.add("brojLicneKarte");
            values.add(idcard);
        }
        
        if(!ime.isEmpty()) {
            columns.add("imeGosta");
            values.add("'"+ime+"'");
        }
        if(!prez.isEmpty()) {
            columns.add("prezimeGosta");
            values.add("'"+prez+"'");
        }
        
        if(!broj.isEmpty()) {
            columns.add("sobaID");
            values.add(broj);
        }
        
        if(vs!=null) {
            columns.add("vrstaSobeID");
            values.add(""+vs.getVrstaSobeID());
        }
        
        /*Request r1 = new Request();
            r1.setOperation(Operacije.PRETRAZI_GOSTE);
            r1.setParam(columnsG);
            r1.setParam2(valuesG);
            
            Komunikacija.getInstance().posaljiZahtev(r1);*/
            
            ///////////////////////////////////Kontroler.getInstanca().pretraziGoste(columnsG, valuesG);
            
            Kontroler.getInstanca().pretraziZakupe(columns, values);
            /*Response response1 = Komunikacija.getInstance().primiOdgovor();
        
            List<Gost> nadjeniGosti = (List<Gost>) response1.getResponse();*/
        
        /*Request r2 = new Request();
        r2.setOperation(Operacije.PRETRAZI_SOBE);
        r2.setParam(columnsS);
        r2.setParam2(valuesS);
        Komunikacija.getInstance().posaljiZahtev(r1);*/
        
        ///////////////////////////////////////////Kontroler.getInstanca().pretraziSobe(columnsS, valuesS);
        
        /*Response response2 = Komunikacija.getInstance().primiOdgovor();
        
        List<Soba> nadjeneSobe = (List<Soba>) response2.getResponse();*/
        
        //DOVRSI METODU////////////////////////////////
        
        /*Request r3 = new Request();
        r3.setOperation(Operacije.VRATI_SVE_ZAKUPE);
        Komunikacija.getInstance().posaljiZahtev(r3);*/
        
        /*Response response3 = Komunikacija.getInstance().primiOdgovor();
        
        List<ZakupSobe> zakupi = (List<ZakupSobe>) response3.getResponse();*/
        
        /*List<ZakupSobe> odgovaraju = new ArrayList<>();
        
        for (ZakupSobe zakupSobe : odgovaraju) {
            for (Gost gost : nadjeniGosti) {
                for (Soba soba : nadjeneSobe) {
                    if(zakupSobe.getGostZakupljuje().getGostId()==gost.getGostId() && zakupSobe.getZakupljenaSoba().getSobaID()==soba.getSobaID()) {
                        odgovaraju.add(zakupSobe);
                    }
                }
            }
        }*/
        
        //rtm.setZakupi(odgovaraju);
        }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jBtnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnableChangesActionPerformed
        RentTableModel rtm = (RentTableModel) jTable1.getModel();
        int red = jTable1.getSelectedRow();
        ZakupSobe zs = rtm.getZakupi().get(red);
        Mapa.getInstanca().setZakup(zs);
        ZakupForma zf = new ZakupForma(null, true, FormMode.FORM_VIEW);
        Kontroler.getInstanca().postaviZakupGormu(zf);
        zf.setVisible(true);
        //dispose();
    }//GEN-LAST:event_jBtnEnableChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEnableChanges;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JComboBox jComboRoomTypes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtIdCard;
    private javax.swing.JTextField jTxtLastname;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtRoomNumber;
    // End of variables declaration//GEN-END:variables

    private void popuniTabelu() {
        
        /*Request r = new Request();
        r.setOperation(Operacije.VRATI_SVE_ZAKUPE);
        Komunikacija.getInstance().posaljiZahtev(r);*/
        Kontroler.getInstanca().vratiSveZakupe();
        
        /*Response response = Komunikacija.getInstance().primiOdgovor();
        System.out.println("USAO");
        ArrayList<ZakupSobe> nadjeniZakupi = (ArrayList<ZakupSobe>) response.getResponse();*/
        //if(nadjeniZakupi == null)System.out.println("NULL");
        /*RentTableModel rmt = new RentTableModel(nadjeniZakupi);
        jTable1.setModel(rmt);*/
        
    }

    private void popuniCombo() {
        //VrstaSobe nista = null;
        
        /*Request r = new Request();
        r.setOperation(Operacije.VRATI_SVE_VRSTE_SOBA); //parametar u zavisnosti koja je forma
        
        Komunikacija.getInstance().posaljiZahtev(r);*/
        
        Kontroler.getInstanca().vratiSveVrsteSoba(Forme.SEARCH_ZAKUP_FORMA);
        
        /*Response response=Komunikacija.getInstance().primiOdgovor();
        
        List<VrstaSobe> vrste = (List<VrstaSobe>) response.getResponse();
        
        jComboRoomTypes.removeAllItems();
        jComboRoomTypes.addItem(nista);
        
        if(vrste==null) {
            System.out.println("NULL JEEE");
        }
        
        for (VrstaSobe vrstaSobe : vrste) {
            jComboRoomTypes.addItem(vrstaSobe);
        }*/
    }

    public void postaviVrste(List<VrstaSobe> vrste) {
        VrstaSobe nista = null;
        jComboRoomTypes.removeAllItems();
        jComboRoomTypes.addItem(nista);
        for (VrstaSobe vrstaSobe : vrste) {
            jComboRoomTypes.addItem(vrstaSobe);
        }
    }

    public void postaviZakupe(List<ZakupSobe> nadjeni) {
        RentTableModel rtm = new RentTableModel(nadjeni);
        jTable1.setModel(rtm);
        
        System.out.println("postavio zakupe");
    }
    
    public void prikaziPoruku(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
    }

    private void prepareForm() {
        setLocationRelativeTo(null);
    }
}
